In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
dataset.head(10) #for 10

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87              NaN  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [4]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [6]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [7]:
dataset["Administration"].mean()

121564.03816326526

In [8]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [9]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)

In [37]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [38]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:].values

In [39]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [40]:
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [41]:

dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [42]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("one",OneHotEncoder(),[3])],remainder = "passthrough")
x = ct.fit_transform(x)

In [43]:
x.shape

(50, 6)

In [44]:
y.shape

(50, 1)

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [46]:
print('x shape ', x.shape)
print('y shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

x shape  (50, 6)
y shape  (50, 1)
x_train shape  (40, 6)
x_test shape  (10, 6)
y_train shape  (40, 1)
y_test shape (10, 1)


In [47]:
x_train.shape

(40, 6)

In [48]:
y_train.shape

(40, 1)

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [51]:
regression = Sequential()

In [52]:
regression.add(Dense(units =6 ,kernel_initializer = "random_uniform",activation = "relu"))

In [53]:
regression.add(Dense(units =12 ,kernel_initializer = "random_uniform",activation = "relu"))

In [54]:
regression.add(Dense(units =12 ,kernel_initializer = "random_uniform",activation = "relu"))

In [55]:
regression.add(Dense( units = 1 , kernel_initializer="random_uniform" , activation = "relu"))

In [56]:
regression.compile(optimizer = "adam",loss = "mse",metrics = ["mse"])

In [57]:
regression.fit(x_train,y_train , epochs = 500)

Epoch 1/500
40/40 [==============================] - 0s 4ms/sample - loss: 13615995289.6000 - mean_squared_error: 13615994880.0000
Epoch 2/500
40/40 [==============================] - 0s 100us/sample - loss: 13615994880.0000 - mean_squared_error: 13615994880.0000
Epoch 3/500
40/40 [==============================] - 0s 85us/sample - loss: 13615994880.0000 - mean_squared_error: 13615994880.0000
Epoch 4/500
40/40 [==============================] - 0s 75us/sample - loss: 13615994880.0000 - mean_squared_error: 13615994880.0000
Epoch 5/500
40/40 [==============================] - 0s 135us/sample - loss: 13615993651.2000 - mean_squared_error: 13615993856.0000
Epoch 6/500
40/40 [==============================] - 0s 77us/sample - loss: 13615993446.4000 - mean_squared_error: 13615993856.0000
Epoch 7/500
40/40 [==============================] - 0s 115us/sample - loss: 13615991808.0000 - mean_squared_error: 13615991808.0000
Epoch 8/500
40/40 [==============================] - 0s 84us/sample - loss

40/40 [==============================] - 0s 152us/sample - loss: 13615808102.4000 - mean_squared_error: 13615808512.0000
Epoch 63/500
40/40 [==============================] - 0s 100us/sample - loss: 13615793561.6000 - mean_squared_error: 13615794176.0000
Epoch 64/500
40/40 [==============================] - 0s 324us/sample - loss: 13615781273.6000 - mean_squared_error: 13615781888.0000
Epoch 65/500
40/40 [==============================] - 0s 80us/sample - loss: 13615766937.6000 - mean_squared_error: 13615766528.0000
Epoch 66/500
40/40 [==============================] - 0s 76us/sample - loss: 13615751577.6000 - mean_squared_error: 13615751168.0000
Epoch 67/500
40/40 [==============================] - 0s 77us/sample - loss: 13615737241.6000 - mean_squared_error: 13615736832.0000
Epoch 68/500
40/40 [==============================] - 0s 139us/sample - loss: 13615720038.4000 - mean_squared_error: 13615720448.0000
Epoch 69/500
40/40 [==============================] - 0s 107us/sample - loss: 

40/40 [==============================] - 0s 76us/sample - loss: 13612193792.0000 - mean_squared_error: 13612193792.0000
Epoch 124/500
40/40 [==============================] - 0s 100us/sample - loss: 13612048384.0000 - mean_squared_error: 13612048384.0000
Epoch 125/500
40/40 [==============================] - 0s 95us/sample - loss: 13611898470.4000 - mean_squared_error: 13611898880.0000
Epoch 126/500
40/40 [==============================] - 0s 100us/sample - loss: 13611741593.6000 - mean_squared_error: 13611742208.0000
Epoch 127/500
40/40 [==============================] - 0s 75us/sample - loss: 13611583488.0000 - mean_squared_error: 13611583488.0000
Epoch 128/500
40/40 [==============================] - 0s 101us/sample - loss: 13611422310.4000 - mean_squared_error: 13611422720.0000
Epoch 129/500
40/40 [==============================] - 0s 76us/sample - loss: 13611245977.6000 - mean_squared_error: 13611245568.0000
Epoch 130/500
40/40 [==============================] - 0s 75us/sample - l

Epoch 184/500
40/40 [==============================] - 0s 146us/sample - loss: 13592143257.6000 - mean_squared_error: 13592143872.0000
Epoch 185/500
40/40 [==============================] - 0s 129us/sample - loss: 13591536844.8000 - mean_squared_error: 13591537664.0000
Epoch 186/500
40/40 [==============================] - 0s 76us/sample - loss: 13590999449.6000 - mean_squared_error: 13591000064.0000
Epoch 187/500
40/40 [==============================] - 0s 76us/sample - loss: 13590367027.2000 - mean_squared_error: 13590367232.0000
Epoch 188/500
40/40 [==============================] - 0s 109us/sample - loss: 13589811507.2000 - mean_squared_error: 13589811200.0000
Epoch 189/500
40/40 [==============================] - 0s 100us/sample - loss: 13589166489.6000 - mean_squared_error: 13589166080.0000
Epoch 190/500
40/40 [==============================] - 0s 77us/sample - loss: 13588570316.8000 - mean_squared_error: 13588570112.0000
Epoch 191/500
40/40 [==============================] - 0s 

40/40 [==============================] - 0s 129us/sample - loss: 13535399731.2000 - mean_squared_error: 13535399936.0000
Epoch 245/500
40/40 [==============================] - 0s 113us/sample - loss: 13533911040.0000 - mean_squared_error: 13533911040.0000
Epoch 246/500
40/40 [==============================] - 0s 101us/sample - loss: 13532572467.2000 - mean_squared_error: 13532572672.0000
Epoch 247/500
40/40 [==============================] - 0s 101us/sample - loss: 13531106099.2000 - mean_squared_error: 13531106304.0000
Epoch 248/500
40/40 [==============================] - 0s 103us/sample - loss: 13529636864.0000 - mean_squared_error: 13529636864.0000
Epoch 249/500
40/40 [==============================] - 0s 125us/sample - loss: 13528133017.6000 - mean_squared_error: 13528132608.0000
Epoch 250/500
40/40 [==============================] - 0s 89us/sample - loss: 13526549299.2000 - mean_squared_error: 13526549504.0000
Epoch 251/500
40/40 [==============================] - 0s 108us/sample

40/40 [==============================] - 0s 75us/sample - loss: 13416099840.0000 - mean_squared_error: 13416099840.0000
Epoch 305/500
40/40 [==============================] - 0s 100us/sample - loss: 13413487820.8000 - mean_squared_error: 13413487616.0000
Epoch 306/500
40/40 [==============================] - 0s 100us/sample - loss: 13410766233.6000 - mean_squared_error: 13410765824.0000
Epoch 307/500
40/40 [==============================] - 0s 75us/sample - loss: 13408038092.8000 - mean_squared_error: 13408037888.0000
Epoch 308/500
40/40 [==============================] - 0s 177us/sample - loss: 13405410918.4000 - mean_squared_error: 13405411328.0000
Epoch 309/500
40/40 [==============================] - 0s 129us/sample - loss: 13402427392.0000 - mean_squared_error: 13402427392.0000
Epoch 310/500
40/40 [==============================] - 0s 102us/sample - loss: 13399812505.6000 - mean_squared_error: 13399812096.0000
Epoch 311/500
40/40 [==============================] - 0s 107us/sample 

40/40 [==============================] - 0s 137us/sample - loss: 13203829145.6000 - mean_squared_error: 13203829760.0000
Epoch 365/500
40/40 [==============================] - 0s 127us/sample - loss: 13199398912.0000 - mean_squared_error: 13199398912.0000
Epoch 366/500
40/40 [==============================] - 0s 104us/sample - loss: 13195010867.2000 - mean_squared_error: 13195011072.0000
Epoch 367/500
40/40 [==============================] - 0s 184us/sample - loss: 13190277529.6000 - mean_squared_error: 13190277120.0000
Epoch 368/500
40/40 [==============================] - 0s 215us/sample - loss: 13185759641.6000 - mean_squared_error: 13185759232.0000
Epoch 369/500
40/40 [==============================] - 0s 155us/sample - loss: 13181089996.8000 - mean_squared_error: 13181089792.0000
Epoch 370/500
40/40 [==============================] - 0s 290us/sample - loss: 13176182988.8000 - mean_squared_error: 13176182784.0000
Epoch 371/500
40/40 [==============================] - 0s 101us/sampl

40/40 [==============================] - 0s 125us/sample - loss: 12859333632.0000 - mean_squared_error: 12859333632.0000
Epoch 425/500
40/40 [==============================] - 0s 138us/sample - loss: 12852418150.4000 - mean_squared_error: 12852418560.0000
Epoch 426/500
40/40 [==============================] - 0s 502us/sample - loss: 12845547110.4000 - mean_squared_error: 12845547520.0000
Epoch 427/500
40/40 [==============================] - 0s 365us/sample - loss: 12838304972.8000 - mean_squared_error: 12838304768.0000
Epoch 428/500
40/40 [==============================] - 0s 182us/sample - loss: 12831610880.0000 - mean_squared_error: 12831610880.0000
Epoch 429/500
40/40 [==============================] - 0s 162us/sample - loss: 12824220672.0000 - mean_squared_error: 12824220672.0000
Epoch 430/500
40/40 [==============================] - 0s 302us/sample - loss: 12817645772.8000 - mean_squared_error: 12817645568.0000
Epoch 431/500
40/40 [==============================] - 0s 103us/sampl

40/40 [==============================] - 0s 75us/sample - loss: 12355699507.2000 - mean_squared_error: 12355699712.0000
Epoch 485/500
40/40 [==============================] - 0s 75us/sample - loss: 12345802342.4000 - mean_squared_error: 12345802752.0000
Epoch 486/500
40/40 [==============================] - 0s 101us/sample - loss: 12335604531.2000 - mean_squared_error: 12335604736.0000
Epoch 487/500
40/40 [==============================] - 0s 103us/sample - loss: 12325396889.6000 - mean_squared_error: 12325396480.0000
Epoch 488/500
40/40 [==============================] - 0s 127us/sample - loss: 12315075993.6000 - mean_squared_error: 12315076608.0000
Epoch 489/500
40/40 [==============================] - 0s 100us/sample - loss: 12305255628.8000 - mean_squared_error: 12305255424.0000
Epoch 490/500
40/40 [==============================] - 0s 55us/sample - loss: 12295023820.8000 - mean_squared_error: 12295023616.0000
Epoch 491/500
40/40 [==============================] - 0s 101us/sample -

In [58]:
ypred = regression.predict(x_test)

In [59]:
ypred

array([[11568.69   ],
       [ 1245.398  ],
       [ 8838.458  ],
       [ 1577.3613 ],
       [12675.689  ],
       [ 7728.521  ],
       [  252.74442],
       [ 5070.237  ],
       [ 8801.534  ],
       [10220.062  ]], dtype=float32)

In [60]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [68]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [69]:
yp = regression.predict(sc.transform(ct.transform([[144372.41, 118671.85, 383199.62, 'New York']])))

In [70]:
yp

array([[11587.609]], dtype=float32)