In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [4]:
dataset.head(10) #for 10

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87              NaN  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [6]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [7]:
dataset["Administration"].mean()

121564.03816326526

In [8]:
dataset["Marketing Spend"].mean()

212725.26673469393

In [9]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace = True)

In [11]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [28]:
x = dataset.iloc[:,0:5].values
y = dataset.iloc[:,5:].values

In [29]:
x

array([[165349.2, 136897.8, 471784.1, 'New York', 192261.83],
       [162597.7, 151377.59, 443898.53, 'California', 191792.06],
       [153441.51, 101145.55, 407934.54, 'Florida', 191050.39],
       [144372.41, 118671.85, 383199.62, 'New York', 182901.99],
       [142107.34, 91391.77, 366168.42, 'Florida', 166187.94],
       [131876.9, 99814.71, 362861.36, 'New York', 156991.12],
       [134615.46, 147198.87, 212725.26673469393, 'California',
        156122.51],
       [130298.13, 145530.06, 323876.68, 'Florida', 155752.6],
       [120542.52, 148718.95, 311613.29, 'New York', 152211.77],
       [123334.88, 108679.17, 304981.62, 'California', 149759.96],
       [101913.08, 121564.03816326526, 229160.95, 'Florida', 146121.95],
       [100671.96, 91790.61, 249744.55, 'California', 144259.4],
       [93863.75, 127320.38, 249839.44, 'Florida', 141585.52],
       [91992.39, 135495.07, 252664.93, 'California', 134307.35],
       [119943.24, 156547.42, 256512.92, 'Florida', 132602.65],
       

In [30]:
y

array([], shape=(50, 0), dtype=float64)

In [31]:

dataset["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("one",OneHotEncoder(),[3])],remainder = "passthrough")
x = ct.fit_transform(x)

In [33]:
x.shape

(50, 7)

In [34]:
y.shape

(50, 0)

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [36]:
print('x shape ', x.shape)
print('y shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

x shape  (50, 7)
y shape  (50, 0)
x_train shape  (40, 7)
x_test shape  (10, 7)
y_train shape  (40, 0)
y_test shape (10, 0)


In [37]:
x_train.shape

(40, 7)

In [38]:
y_train.shape

(40, 0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [41]:
regression = Sequential()

In [42]:
regression.add(Dense(units =6 ,kernel_initializer = "random_uniform",activation = "relu"))

In [43]:
regression.add(Dense(units =12 ,kernel_initializer = "random_uniform",activation = "relu"))

In [44]:
regression.add(Dense(units =12 ,kernel_initializer = "random_uniform",activation = "relu"))

In [45]:
regression.add(Dense( units = 1 , kernel_initializer="random_uniform" , activation = "relu"))

In [46]:
regression.compile(optimizer = "adam",loss = "mse",metrics = ["mse"])

In [78]:
regression.fit(x_train,y_train , epochs = 500)

Epoch 1/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 2/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 3/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 4/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 5/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 6/500
40/40 [==============================] - 0s 150us/sample - loss: nan - mean_squared_error: nan
Epoch 7/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 8/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 9/500
40/40 [==============================] - 0s 150us/sample - loss: nan - mean_squared_error: nan
Epoch 10/500
40/40 [===================

40/40 [==============================] - 0s 150us/sample - loss: nan - mean_squared_error: nan
Epoch 78/500
40/40 [==============================] - 0s 150us/sample - loss: nan - mean_squared_error: nan
Epoch 79/500
40/40 [==============================] - 0s 149us/sample - loss: nan - mean_squared_error: nan
Epoch 80/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 81/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 82/500
40/40 [==============================] - 0s 50us/sample - loss: nan - mean_squared_error: nan
Epoch 83/500
40/40 [==============================] - 0s 97us/sample - loss: nan - mean_squared_error: nan
Epoch 84/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 85/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 86/500
40/40 [=======================

40/40 [==============================] - 0s 99us/sample - loss: nan - mean_squared_error: nan
Epoch 153/500
40/40 [==============================] - 0s 76us/sample - loss: nan - mean_squared_error: nan
Epoch 154/500
40/40 [==============================] - 0s 124us/sample - loss: nan - mean_squared_error: nan
Epoch 155/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 156/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 157/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 158/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 159/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 160/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 161/500
40/40 [=================

40/40 [==============================] - 0s 99us/sample - loss: nan - mean_squared_error: nan
Epoch 228/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 229/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 230/500
40/40 [==============================] - 0s 99us/sample - loss: nan - mean_squared_error: nan
Epoch 231/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 232/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 233/500
40/40 [==============================] - 0s 49us/sample - loss: nan - mean_squared_error: nan
Epoch 234/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 235/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 236/500
40/40 [==================

40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 303/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 304/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 305/500
40/40 [==============================] - 0s 51us/sample - loss: nan - mean_squared_error: nan
Epoch 306/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 307/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 308/500
40/40 [==============================] - 0s 74us/sample - loss: nan - mean_squared_error: nan
Epoch 309/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 310/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 311/500
40/40 [===============

40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 378/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 379/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 380/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 381/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 382/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 383/500
40/40 [==============================] - 0s 74us/sample - loss: nan - mean_squared_error: nan
Epoch 384/500
40/40 [==============================] - 0s 74us/sample - loss: nan - mean_squared_error: nan
Epoch 385/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 386/500
40/40 [=================

40/40 [==============================] - 0s 98us/sample - loss: nan - mean_squared_error: nan
Epoch 453/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 454/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 455/500
40/40 [==============================] - 0s 98us/sample - loss: nan - mean_squared_error: nan
Epoch 456/500
40/40 [==============================] - 0s 73us/sample - loss: nan - mean_squared_error: nan
Epoch 457/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 458/500
40/40 [==============================] - 0s 75us/sample - loss: nan - mean_squared_error: nan
Epoch 459/500
40/40 [==============================] - 0s 100us/sample - loss: nan - mean_squared_error: nan
Epoch 460/500
40/40 [==============================] - 0s 125us/sample - loss: nan - mean_squared_error: nan
Epoch 461/500
40/40 [==================

In [79]:
ypred = regression.predict(x_test)

In [80]:
ypred

array([[-0.0000000e+00],
       [ 2.6767993e-06],
       [ 1.3525583e-05],
       [-0.0000000e+00],
       [ 2.6067290e-05],
       [-0.0000000e+00],
       [-0.0000000e+00],
       [-0.0000000e+00],
       [ 4.9832743e-06],
       [ 2.0263791e-05]], dtype=float32)

In [81]:
y_test

array([], shape=(10, 0), dtype=float64)

In [82]:
dataset.head(1)

R&D Spend  Administration  Marketing Spend     State     Profit
0   165349.2        136897.8         471784.1  New York  192261.83

In [89]:
yp=regression.predict(sc.transform(ct.transform([[165349.2,136897.8,471784.1,'New York',192261.83]])))

In [93]:
deposit = ["no","yes"]
prediction = deposit[np.argmax(yp)]

In [95]:
yp

array([[2.1365708e-05]], dtype=float32)

In [96]:
yp<0.5

array([[ True]])