In [1]:
import seaborn as sb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("bank.csv")

In [3]:
data

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [4]:
data.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null object
marital      11162 non-null object
education    11162 non-null object
default      11162 non-null object
balance      11162 non-null int64
housing      11162 non-null object
loan         11162 non-null object
contact      11162 non-null object
day          11162 non-null int64
month        11162 non-null object
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null object
deposit      11162 non-null object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [7]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [12]:
x=data.iloc[:,:-6].values
y=data.iloc[:,14].values

In [13]:
x.shape

(11162, 11)

In [14]:
x

array([[59, 'admin.', 'married', ..., 'unknown', 5, 'may'],
       [56, 'admin.', 'married', ..., 'unknown', 5, 'may'],
       [41, 'technician', 'married', ..., 'unknown', 5, 'may'],
       ...,
       [32, 'technician', 'single', ..., 'cellular', 19, 'aug'],
       [43, 'technician', 'married', ..., 'cellular', 8, 'may'],
       [34, 'technician', 'married', ..., 'cellular', 9, 'jul']],
      dtype=object)

In [15]:
y.shape

(11162,)

In [16]:
y

array([0, 0, 0, ..., 0, 5, 0], dtype=int64)

In [18]:
type(x)

numpy.ndarray

In [19]:
type(y)

numpy.ndarray

In [20]:
data.T

0          1           2          3         4           5      \
age               59         56          41         55        54          42   
job           admin.     admin.  technician   services    admin.  management   
marital      married    married     married    married   married      single   
education  secondary  secondary   secondary  secondary  tertiary    tertiary   
default           no         no          no         no        no          no   
balance         2343         45        1270       2476       184           0   
housing          yes         no         yes        yes        no         yes   
loan              no         no          no         no        no         yes   
contact      unknown    unknown     unknown    unknown   unknown     unknown   
day                5          5           5          5         5           5   
month            may        may         may        may       may         may   
duration        1042       1467        1389        579       673         562   
campaign           1          1           1          1         2           2   
pdays             -1         -1          -1         -1        -1          -1   
previous           0          0           0          0         0           0   
poutcome     unknown    unknown     unknown    unknown   unknown     unknown   
deposit          yes        yes         yes        yes       yes         yes   

                6          7           8          9      ...      11152  \
age                56         60          37         28  ...         34   
job        management    retired  technician   services  ...  housemaid   
marital       married   divorced     married     single  ...    married   
education    tertiary  secondary   secondary  secondary  ...  secondary   
default            no         no          no         no  ...         no   
balance           830        545           1       5090  ...        390   
housing           yes        yes         yes        yes  ...        yes   
loan              yes         no          no         no  ...         no   
contact       unknown    unknown     unknown    unknown  ...   cellular   
day                 6          6           6          6  ...         15   
month             may        may         may        may  ...        jul   
duration         1201       1030         608       1297  ...        659   
campaign            1          1           1          3  ...          3   
pdays              -1         -1          -1         -1  ...         -1   
previous            0          0           0          0  ...          0   
poutcome      unknown    unknown     unknown    unknown  ...    unknown   
deposit           yes        yes         yes        yes  ...         no   

               11153       11154        11155        11156        11157  \
age               43          52           35           34           33   
job           admin.  technician  blue-collar  blue-collar  blue-collar   
marital       single     married      married       single       single   
education  secondary    tertiary    secondary    secondary      primary   
default           no          no           no           no           no   
balance           35         523           80          -72            1   
housing           no         yes          yes          yes          yes   
loan              no         yes          yes           no           no   
contact    telephone    cellular     cellular     cellular     cellular   
day                9           8           21            7           20   
month            nov         jul          nov          jul          apr   
duration         208         113           38          273          257   
campaign           1           1            2            5            1   
pdays             -1          -1          172           -1           -1   
previous           0           0            2            0            0   
poutcome     unknown   

In [23]:
from sklearn.compose import ColumnTransformer

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7])],remainder ="passthrough")
x = ct.fit_transform(x)

C:\Users\dival\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [46]:
x[0]

array([1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0,
       1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0,
       1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 59, 2343, 'unknown', 5, 'may'],
      dtype=object)

In [29]:
x.shape

(11162, 36)

In [32]:
y[0]

0

In [36]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [37]:
print(x.shape,"XShape")
print(y.shape,"YShape")
print(x_train.shape,"Xtrain")
print(y_train.shape,"Ytrain")
print(x_test.shape,"Xtest")
print(y_test.shape,"Ytest")

(11162, 36) XShape
(11162,) YShape
(8929, 36) Xtrain
(8929,) Ytrain
(2233, 36) Xtest
(2233,) Ytest


In [40]:
x_train[0:5,:]

array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 1.0, 1.0, 0.0, 49, 104, 'unknown', 8, 'may'],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 59, 514, 'cellular', 3, 'feb'],
       [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 33, 195, 'cellular', 16, 'nov'],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 1.0, 1.0, 0.0, 58, 687, 'cellular', 7, 'aug'],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
        0.